name: Run Python Script with Arguments from New Commits

on:
  pull_request:
    paths:
      - 'modules.json'
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Extract arguments from new commits
        id: extract_args
        run: |
          COMMITS=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits" | jq -r '.[].sha')

          ARGS=""
          for COMMIT in $COMMITS; do
            # Extraer cambios del archivo "modules.json" en cada commit
            DIFF=$(git diff $COMMIT~1 $COMMIT -- modules.json || true)
            NEW_KEYS=$(echo "$DIFF" | grep '^+' | grep '"key"' | jq -r '.key' || true)
            ARGS="$ARGS $NEW_KEYS"
          done

          # Pasar los argumentos extraídos como salida
          echo "commit_args=$(echo $ARGS | tr -s ' ')" >> $GITHUB_OUTPUT

      - name: Run Python script with arguments
        run: python test.py ${{ steps.extract_args.outputs.commit_args }}
